### ISSUE TITLE
Talk rating not working

### ISSUE THREAD

**Issue by ghost** [devoxx/AndroidMobileApp#16]
The app is just displaying "something went wrong" error message. Happens on android 5.1.1.
Reinstalling, clearing data or killing application isn't fixing the issue.

**Comment by jmodrako** [comment]
Hello @the4dk!

Thanks for the information, we've had some server problems with voting. But now it's working :)

Can you clear app data and try again?

**Comment by saw303** [comment]
does not work for me?

**Comment by jmodrako** [comment]
Hi @saw303!

Did you clear app data? Be sure to clear data, not the cache. Ping me if it's working.

**Comment by ghost** [comment]
@jmodrako It's working for me now. @saw303, you need to clear the app data first.

**Comment by saw303** [comment]
okay it does work now. app data clearing did the job

**Comment by thorgull** [comment]
This solution does not fix the problem for me. Still getting "something went wrong"  after clearing the application data.

**Comment by NangiDev** [comment]
Same here. I tried clearing application data.

**Comment by jmodrako** [comment]
I'm going to see what's happening.

**Comment by jmodrako** [comment]
@thorgull @settrbrg Can you tell me what Android version are you using, also, current language of the device, and the application version.

**Comment by jmodrako** [comment]
@thorgull @settrbrg Can you look guys at this build? Please let me know if that will work for you.

https://dl.dropboxusercontent.com/u/68360638/app-my-devoxx-135.apk

**Comment by thorgull** [comment]
![tmp_17774-screenshot_2016-11-07-16-14-13-606786770](https://cloud.githubusercontent.com/assets/13849054/20062814/614a1124-a505-11e6-81ed-10db0730265d.png)
I get that error.

**Comment by NangiDev** [comment]
@jmodrako
Android version: 6.0.1
Language: Swedish
Huntly version: 3.2.2

**Comment by jmodrako** [comment]
Ok thanks @thorgull Can you uninstall previous version and install provided one from dropbox above as fresh install?

**Comment by NangiDev** [comment]
I get the same error as thorgull with the version you sent.

**Comment by thorgull** [comment]
Work like a charm after Uninstaller / install new version.

**Comment by NangiDev** [comment]
I uninstalled the MyDevoxx and installed the One you sent. It worked! :)

**Comment by jmodrako** [comment]
Ok Awesome, thanks guys for the help! I'm uploading new version to Play Store. Big thanks. Closing issue! ;)
