### ISSUE TITLE
No data yet available

### ISSUE THREAD

**Issue by gerhard-hiller** [devoxx/AndroidMobileApp#20]
After having a working Version I Updated to the newest version yesterday. No I always get the following Error:

![screenshot_2016-10-27-16-09-16](https://cloud.githubusercontent.com/assets/23101872/19771687/0f354358-9c64-11e6-8dbc-88f643d0cf8e.png)

Any idea? Clear data, cache and unistall/install didn't help

**Comment by jmodrako** [comment]
Hello @gerhard-hiller thanks for the info. Can you tell me what android version are you using? Also it seems that you are working on HSDPA mobile connection. Can you try open the app on wi-fi?

**Comment by thorgull** [comment]
Same problem on Sony xperia z3 tablet compact Android 5.1.1 connected on WiFi at home. (Proximus network)

**Comment by bagges** [comment]
Same here. Nexus 5X with Android 7. Clear Data/Cache did not help.

**Comment by jmodrako** [comment]
Guys can you install this debug version of the app? It will show you number of downloaded talks, for specific days, if you could write down here the stats that would be helpful. Thanks!

https://dl.dropboxusercontent.com/u/68360638/my-devoxx-dev.apk

**Comment by stephanj** [comment]
The normal and debug versions work fine on my Samsung S6 and Nexus 6.
Debug msg says : 263 talks downloaded for Devoxx BE.

**Comment by thorgull** [comment]
Debug Apps says :
Downloading for: [lundi, mardi, mercredi, jeudi, vendredi] 
Downloaded: 0
No data yet available

**Comment by jmodrako** [comment]
Thanks @thorgull I know what is wrong, day names is in wrong language...

**Comment by thorgull** [comment]
I just looked in previous commits, 
Maybe is about this new line in SlotDownloader.java
- final String dayName = start.dayOfWeek().getAsText().toLowerCase();
  getAsText()  return localized version...

**Comment by jmodrako** [comment]
Yeah @thorgull, I've had to add `Locale` as argument for `getAsText()`  I've fixed it and doing tests. Update will be available later today. Thanks for the help all!

Fixed by: [bc7df17f3d3d948985](https://github.com/devoxx/AndroidMobileApp/commit/bc7df17f3d3d9489852663faa92727371e2e9fce)
