### ISSUE TITLE
Voting on Android returns an Error

### ISSUE THREAD

**Issue by waterfif** [devoxx/AndroidMobileApp#26]
Hi, 

I have a Nexus 6 Android phone running Android 7.0. 

1) I open MyDevoxx and click on a talk I wish to rate. 
2) click on the heart icon
3) select my star rating and click on  Vote

I get a toast message that says "Something went wrong"

There are no further indications as to what went wrong. 

I have good internet connection.

**Comment by jmodrako** [comment]
Hello @waterfif, thanks for the info, we are released update couple days ago with fix, please install the newest version from Google Play (v x.x.135) and then please rescan your qr badge (settings->clear->scan QR)

https://pbs.twimg.com/media/CwrQIJuXEAAhltV.jpg

**Comment by waterfif** [comment]
Many thanks for the swift response
