### ISSUE TITLE
"Starred" talks lost after reboot

### ISSUE THREAD

**Issue by jljouannic** [devoxx/AndroidMobileApp#7]
Each time I reboot my phone, I can not identify which talk I had voted for (by clicking on the star). They are all gone. Instead I get tens of notifications inviting me to vote for the same talks I had previously voted for. Very frustrating.

**Comment by jmodrako** [comment]
Hi @jljouannic! Thanks for the info about it, we are working on this issue.

**Comment by jmodrako** [comment]
@jljouannic here you can grab the newest version of MyDevoxx:

[MyDevoxx Files](https://drive.google.com/folderview?id=0BwNp2lR4-TN3WkZndFR3SU02bkk&usp=sharing)

Please do following test:
1. Install app from Google Play (v116)
2. Add some favs.
3. Do update to v118 from the above link.
4. Check whether your favs are still in the app.

**Comment by jljouannic** [comment]
Problem solved. Thank you! I let you close the issue.

**Comment by jmodrako** [comment]
Awesome @jljouannic :) Thanks for tests :)
