### ISSUE TITLE
talk does not exists when voting

### ISSUE THREAD

**Issue by whren** [devoxx/AndroidMobileApp#8]
On the updated version 1.0.119, when you try to vote you'll get a "talk xxx does not exists"

**Comment by jmodrako** [comment]
Hello @whren! 

Thanks for the info about issue, you mean the message is "Talk xxx does not exist"?

Can you tell me the exact talk title?

**Comment by whren** [comment]
For example talk 'GNM-4990', named "Keynote de l'équipe Devoxx France", or 'XJJ-2449' named "La médecine de demain"

**Comment by VBoulin** [comment]
I've got the same issue with every talks (same version 1.0.119)

For exemple: Talk GNM-4990 does not exist

**Comment by notflorian** [comment]
I've the same issue when I tried to vote for the first 3 keynote of DevoxxFr.

**Comment by notflorian** [comment]
It look like it fixed, I've succed to vote for the keynotes

**Comment by jmodrako** [comment]
Thanks @notflorian for the info. Closing.
